#!/usr/bin/python

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import utils
import email, random, os, time, datetime, socket, email.mime.application, string
''' This file is meant to build the appropriate parts of the phishing message
and will be called by phishing.py. Much more will be added to this to simplify the
idea of building the messages and whatnot.'''


URL_Placemarker = 'URL_Placemarker'

def make_msgid(idstring=None):
    """Returns a string suitable for RFC 2822 compliant Message-ID
    Optional idstring if given is a string used to strengthen the
    uniqueness of the message id.
    """
    timeval = int(time.time()*100)
    pid = os.getpid()
    randint = random.getrandbits(64)
    if idstring is None:
        idstring = ''
    else:
        idstring = '.' + idstring
    idhost = socket.getfqdn()
    msgid = '<%d.%d.%d%s@%s>' % (timeval, pid, randint, idstring, idhost)
    return msgid

def build_body(variable_dict):

    MaskedURL = variable_dict['link']
    if MaskedURL == '':
        MaskedURL = URL_Placemarker

    client = variable_dict['client']
    if client == '':
        client = 'NO CLIENT'
    sender_in_header = variable_dict['headerfrom']
    if sender_in_header == '':
        sender_in_header = 'IT Support <ITSupport@contoso.com>'

    rand_id = ''.join([random.choice(string.ascii_letters + string.digits) for n in xrange(15)])
    msgid = make_msgid(rand_id)

    currentDate = utils.formatdate(timeval=None, localtime=True, usegmt=False)
    d = str(datetime.datetime.today().strftime("%A, %B %d %Y @ %I:%M%p"))
    delta = datetime.timedelta(days=7)
    expireDate = (datetime.datetime.strptime(d,  "%A, %B %d %Y @ %I:%M%p") + delta).strftime("%A, %B %d %Y @ %I:%M%p")

    msg = MIMEMultipart('alternative')
    msg['From'] = sender_in_header
    msg['To'] = 'EMPADDR'
    msg['Subject'] = 'Secure Message from {0}'.format(client)
    msg['Date'] = currentDate
    msg['message-id'] = msgid

    plaintextBody ="""New ZixCorp secure email message from {0}\n
To view the secure message, click on the link below or copy and paste the
link into your Internet browser address bar.\n
{1}\n
You are reading the plaintext version of this message.  For a better user
experience, change your email settings to enable the viewing of HTML.\n
Do not reply to this notification message; this message was auto-generated
by the sender's security system. To reply to the sender, click on the link
above.

The secure message expires on {2}.
""".format(client, URL_Placemarker, expireDate)

    htmlBody ='''
<table width=3D"100%%"><tr><td><table width=3D"100%%" cellpadding=3D"0" cell=
spacing=3D"1"><tr bgColor=3D"#999999"><td height=3D"1"></td></tr><tr bgColo=
r=3D"#999999"><td height=3D"2"></td></tr><tr><td><table width=3D"100%%" bord=
er=3D"0" cellspacing=3D"1" cellpadding=3D"1"><tr><td height=3D"1"></td></tr=
><tr bgColor=3D"#f2f2f2"><td><table width=3D"100%%" cellspacing=3D"1" cellpa=
dding=3D"12"><tr><td><b><font face=3D"arial" size=3D"4">New ZixCorp secure =
email message from %s</font></b></td></tr></table></td></tr><tr><td hei=
ght=3D"2"></td></tr></table></td></tr><tr bgColor=3D"#999999"><td height=3D=
"3"></td></tr><tr bgColor=3D"#999999"><td height=3D"2"></td></tr></table></=
td></tr></table><table width=3D"75%%" cellpadding=3D"10"><tr><td><table bgc=
olor=3D"#999999" cellspacing=3D"2" cellpadding=3D"4" border=3D"0"><tr bgcol=
or=3D"#b9b9b9"><td><a href=3D\"%s\" style=3D"text-de=coration: none; display:inline-block; cursor: pointer;background-color: #b9=
b9b9; color: #ffffff; font-family: arial; font-size: 18px; font-weight: bol=
d;text-align: center; text-shadow: 0 -1px 0 #4D4D4D; padding: 10px 14px 10p=
x 14px; border-width: 2px;border-color: #999999;">Open Message</a></td></tr=
></table></td></tr><tr><td><font face=3D"arial" size=3D"2"><p>To view the s=
ecure message, click Open Message.</p><p>The secure message expires on %s.</p><p>Do not reply to this notification message;=
 this message was auto-generated by the sender\'s security system. To reply =
to the sender, click Open Message.</p><p>If clicking Open Message does not =
work, copy and paste the link below into your Internet browser address bar.<br>=
<br/><a href=3D\"%s\">%s</a></p></font></td></tr></table>
    ''' %(client, URL_Placemarker,expireDate,URL_Placemarker,MaskedURL)

    # File attachment
    if variable_dict['attachment'] != '':
        filename = variable_dict['attachment']
        fp = open(filename,'rb')
        extension = filename.rsplit('.', 1)[-1]
        att = email.mime.application.MIMEApplication(fp.read(),_subtype=extension)
        fp.close()
        att.add_header('Content-Disposition','attachment',filename=filename)
        msg.attach(att)

    part1 = MIMEText(plaintextBody, 'plain')
    part2 = MIMEText(htmlBody, 'html')
    part2.replace_header('Content-Transfer-Encoding', 'quoted-printable')

    # Attach parts into message container.
    # According to RFC 2046, the last part of a multipart message, in this case
    # the HTML message, is best and preferred.
    msg.attach(part1)
    msg.attach(part2)
    return msg.as_string()
